// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {
            "name": "API Support",
            "email": "mmishin2107@gmail.com"
        },
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/api/v1/auth/refresh": {
            "post": {
                "description": "Refreshes access and refresh tokens using valid refresh token from cookies",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "auth"
                ],
                "summary": "Refresh tokens",
                "parameters": [
                    {
                        "enum": [
                            "true"
                        ],
                        "type": "string",
                        "description": "Must be 'true'",
                        "name": "goyda",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "204": {
                        "description": "Successful updated"
                    },
                    "400": {
                        "description": "Invalid request or validation error",
                        "schema": {
                            "$ref": "#/definitions/dto.HTTPStatus"
                        }
                    },
                    "401": {
                        "description": "Unauthorized - invalid/missing refresh token",
                        "schema": {
                            "$ref": "#/definitions/dto.HTTPStatus"
                        }
                    },
                    "500": {
                        "description": "Internal server error",
                        "schema": {
                            "$ref": "#/definitions/dto.HTTPStatus"
                        }
                    }
                }
            }
        },
        "/api/v1/category": {
            "get": {
                "description": "Retrieves a list of category filtered by category, volume, title, etc.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "category"
                ],
                "summary": "Get category by filters",
                "parameters": [
                    {
                        "maximum": 100,
                        "minimum": 1,
                        "type": "integer",
                        "description": "Max number of items",
                        "name": "limit",
                        "in": "query"
                    },
                    {
                        "minimum": 0,
                        "type": "integer",
                        "description": "Offset for pagination",
                        "name": "offset",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/dto.Category"
                            }
                        }
                    },
                    "400": {
                        "description": "Invalid query parameters",
                        "schema": {
                            "$ref": "#/definitions/dto.HTTPStatus"
                        }
                    },
                    "500": {
                        "description": "Internal server error",
                        "schema": {
                            "$ref": "#/definitions/dto.HTTPStatus"
                        }
                    }
                }
            },
            "post": {
                "security": [
                    {
                        "CookieAuth": []
                    }
                ],
                "description": "Creates a new category product with provided details.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "category"
                ],
                "summary": "Create a new category product",
                "parameters": [
                    {
                        "description": "Category product data",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/dto.CreateCategoryRequest"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "$ref": "#/definitions/dto.CreateCategoryResponse"
                        }
                    },
                    "400": {
                        "description": "Invalid request body or validation error",
                        "schema": {
                            "$ref": "#/definitions/dto.HTTPStatus"
                        }
                    },
                    "409": {
                        "description": "Conflict: invalid category format",
                        "schema": {
                            "$ref": "#/definitions/dto.HTTPStatus"
                        }
                    },
                    "500": {
                        "description": "Internal server error",
                        "schema": {
                            "$ref": "#/definitions/dto.HTTPStatus"
                        }
                    }
                }
            }
        },
        "/api/v1/category/{id}": {
            "get": {
                "description": "Retrieves a category product using its UUID.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "category"
                ],
                "summary": "Get category by ID",
                "parameters": [
                    {
                        "type": "string",
                        "format": "uuid",
                        "description": "Cosmetic ID (UUID)",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/dto.GetByIdCategoryResponse"
                        }
                    },
                    "400": {
                        "description": "Validation error",
                        "schema": {
                            "$ref": "#/definitions/dto.HTTPStatus"
                        }
                    },
                    "404": {
                        "description": "Cosmetic not found",
                        "schema": {
                            "$ref": "#/definitions/dto.HTTPStatus"
                        }
                    },
                    "500": {
                        "description": "Internal server error",
                        "schema": {
                            "$ref": "#/definitions/dto.HTTPStatus"
                        }
                    }
                }
            },
            "delete": {
                "security": [
                    {
                        "CookieAuth": []
                    }
                ],
                "description": "Deletes the category product with the given UUID.",
                "tags": [
                    "category"
                ],
                "summary": "Delete category by ID",
                "parameters": [
                    {
                        "type": "string",
                        "format": "uuid",
                        "description": "Category ID (UUID)",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "204": {
                        "description": "Successfully deleted"
                    },
                    "400": {
                        "description": "Validation error",
                        "schema": {
                            "$ref": "#/definitions/dto.HTTPStatus"
                        }
                    },
                    "404": {
                        "description": "Category not found",
                        "schema": {
                            "$ref": "#/definitions/dto.HTTPStatus"
                        }
                    },
                    "500": {
                        "description": "Internal server error",
                        "schema": {
                            "$ref": "#/definitions/dto.HTTPStatus"
                        }
                    }
                }
            },
            "patch": {
                "security": [
                    {
                        "CookieAuth": []
                    }
                ],
                "description": "Updates category product fields by given ID.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "category"
                ],
                "summary": "Update category",
                "parameters": [
                    {
                        "type": "string",
                        "format": "uuid",
                        "description": "Cosmetic ID (UUID)",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Updated category fields",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/dto.UpdateCategoryRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/dto.UpdateCategoryResponse"
                        }
                    },
                    "400": {
                        "description": "Validation or binding error",
                        "schema": {
                            "$ref": "#/definitions/dto.HTTPStatus"
                        }
                    },
                    "404": {
                        "description": "Cosmetic not found",
                        "schema": {
                            "$ref": "#/definitions/dto.HTTPStatus"
                        }
                    },
                    "500": {
                        "description": "Internal server error",
                        "schema": {
                            "$ref": "#/definitions/dto.HTTPStatus"
                        }
                    }
                }
            }
        },
        "/api/v1/cosmetics": {
            "get": {
                "description": "Retrieves a list of cosmetics filtered by category, volume, title, etc.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "cosmetics"
                ],
                "summary": "Get cosmetics by filters",
                "parameters": [
                    {
                        "maximum": 100,
                        "minimum": 1,
                        "type": "integer",
                        "description": "Max number of items",
                        "name": "limit",
                        "in": "query"
                    },
                    {
                        "minimum": 0,
                        "type": "integer",
                        "description": "Offset for pagination",
                        "name": "offset",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "format": "uuid",
                        "example": "123e4567-e89b-12d3-a456-426614174000",
                        "description": "Category UUID",
                        "name": "category_id",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Filter by title prefix",
                        "name": "titlePrefix",
                        "in": "query"
                    },
                    {
                        "maximum": 10000,
                        "minimum": 1,
                        "type": "integer",
                        "description": "Exact volume in ml",
                        "name": "volume",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/dto.Cosmetics"
                            }
                        }
                    },
                    "400": {
                        "description": "Invalid query parameters",
                        "schema": {
                            "$ref": "#/definitions/dto.HTTPStatus"
                        }
                    },
                    "500": {
                        "description": "Internal server error",
                        "schema": {
                            "$ref": "#/definitions/dto.HTTPStatus"
                        }
                    }
                }
            },
            "post": {
                "security": [
                    {
                        "CookieAuth": []
                    }
                ],
                "description": "Creates a new cosmetic product with provided details.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "cosmetics"
                ],
                "summary": "Create a new cosmetic product",
                "parameters": [
                    {
                        "description": "Cosmetic product data",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/dto.CreateCosmeticsRequest"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "$ref": "#/definitions/dto.CreateCosmeticsResponse"
                        }
                    },
                    "400": {
                        "description": "Invalid request body or validation error",
                        "schema": {
                            "$ref": "#/definitions/dto.HTTPStatus"
                        }
                    },
                    "409": {
                        "description": "Conflict: invalid cosmetics format",
                        "schema": {
                            "$ref": "#/definitions/dto.HTTPStatus"
                        }
                    },
                    "500": {
                        "description": "Internal server error",
                        "schema": {
                            "$ref": "#/definitions/dto.HTTPStatus"
                        }
                    }
                }
            }
        },
        "/api/v1/cosmetics/admin": {
            "get": {
                "description": "Retrieves a list of cosmetics filtered by category, volume, title, etc and hidden parameters.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "cosmetics"
                ],
                "summary": "Get cosmetics by filters",
                "parameters": [
                    {
                        "maximum": 100,
                        "minimum": 1,
                        "type": "integer",
                        "description": "Max number of items",
                        "name": "limit",
                        "in": "query"
                    },
                    {
                        "minimum": 0,
                        "type": "integer",
                        "description": "Offset for pagination",
                        "name": "offset",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "format": "uuid",
                        "example": "123e4567-e89b-12d3-a456-426614174000",
                        "description": "Category UUID",
                        "name": "category_id",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Filter by title prefix",
                        "name": "titlePrefix",
                        "in": "query"
                    },
                    {
                        "maximum": 10000,
                        "minimum": 1,
                        "type": "integer",
                        "description": "Exact volume in ml",
                        "name": "volume",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/dto.Cosmetics"
                            }
                        }
                    },
                    "400": {
                        "description": "Invalid query parameters",
                        "schema": {
                            "$ref": "#/definitions/dto.HTTPStatus"
                        }
                    },
                    "500": {
                        "description": "Internal server error",
                        "schema": {
                            "$ref": "#/definitions/dto.HTTPStatus"
                        }
                    }
                }
            }
        },
        "/api/v1/cosmetics/{id}": {
            "get": {
                "description": "Retrieves a cosmetic product using its UUID.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "cosmetics"
                ],
                "summary": "Get cosmetic by ID",
                "parameters": [
                    {
                        "type": "string",
                        "format": "uuid",
                        "description": "Cosmetic ID (UUID)",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/dto.GetByIdCosmeticsResponse"
                        }
                    },
                    "400": {
                        "description": "Validation error",
                        "schema": {
                            "$ref": "#/definitions/dto.HTTPStatus"
                        }
                    },
                    "404": {
                        "description": "Cosmetic not found",
                        "schema": {
                            "$ref": "#/definitions/dto.HTTPStatus"
                        }
                    },
                    "500": {
                        "description": "Internal server error",
                        "schema": {
                            "$ref": "#/definitions/dto.HTTPStatus"
                        }
                    }
                }
            },
            "delete": {
                "security": [
                    {
                        "CookieAuth": []
                    }
                ],
                "description": "Deletes the cosmetic product with the given UUID.",
                "tags": [
                    "cosmetics"
                ],
                "summary": "Delete cosmetic by ID",
                "parameters": [
                    {
                        "type": "string",
                        "format": "uuid",
                        "description": "Cosmetic ID (UUID)",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "204": {
                        "description": "Successfully deleted"
                    },
                    "400": {
                        "description": "Validation error",
                        "schema": {
                            "$ref": "#/definitions/dto.HTTPStatus"
                        }
                    },
                    "404": {
                        "description": "Cosmetic not found",
                        "schema": {
                            "$ref": "#/definitions/dto.HTTPStatus"
                        }
                    },
                    "500": {
                        "description": "Internal server error",
                        "schema": {
                            "$ref": "#/definitions/dto.HTTPStatus"
                        }
                    }
                }
            },
            "patch": {
                "security": [
                    {
                        "CookieAuth": []
                    }
                ],
                "description": "Updates cosmetic product fields by given ID.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "cosmetics"
                ],
                "summary": "Update cosmetic",
                "parameters": [
                    {
                        "type": "string",
                        "format": "uuid",
                        "description": "Cosmetic ID (UUID)",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Updated cosmetic fields",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/dto.UpdateCosmeticsRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/dto.UpdateCosmeticsResponse"
                        }
                    },
                    "400": {
                        "description": "Validation or binding error",
                        "schema": {
                            "$ref": "#/definitions/dto.HTTPStatus"
                        }
                    },
                    "404": {
                        "description": "Cosmetic not found",
                        "schema": {
                            "$ref": "#/definitions/dto.HTTPStatus"
                        }
                    },
                    "500": {
                        "description": "Internal server error",
                        "schema": {
                            "$ref": "#/definitions/dto.HTTPStatus"
                        }
                    }
                }
            }
        },
        "/api/v1/info/corporation": {
            "get": {
                "description": "Returns the current public corporation information: heading, description, fluid status, schedule, and links.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "info"
                ],
                "summary": "Get corporation info",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/dto.GetInfoResponse"
                        }
                    },
                    "500": {
                        "description": "Internal server error",
                        "schema": {
                            "$ref": "#/definitions/dto.HTTPStatus"
                        }
                    }
                }
            },
            "patch": {
                "security": [
                    {
                        "CookieAuth": []
                    }
                ],
                "description": "Updates the corporation info fields. Only accessible by authenticated moderators.\nRequires authentication via cookies (access_token, refresh_token)",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "info"
                ],
                "summary": "UpdateCurrent corporation info",
                "parameters": [
                    {
                        "description": "Updated corporation info",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/dto.UpdateInfoRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/dto.UpdateInfoResponse"
                        }
                    },
                    "400": {
                        "description": "Validation error",
                        "schema": {
                            "$ref": "#/definitions/dto.HTTPStatus"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/dto.HTTPStatus"
                        }
                    },
                    "403": {
                        "description": "Forbidden",
                        "schema": {
                            "$ref": "#/definitions/dto.HTTPStatus"
                        }
                    },
                    "500": {
                        "description": "Internal server error",
                        "schema": {
                            "$ref": "#/definitions/dto.HTTPStatus"
                        }
                    }
                }
            }
        },
        "/api/v1/info/partner": {
            "get": {
                "description": "Retrieves a list of partners with pagination.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "partner"
                ],
                "summary": "Get partners with pagination",
                "parameters": [
                    {
                        "maximum": 100,
                        "minimum": 1,
                        "type": "integer",
                        "description": "Max number of items",
                        "name": "limit",
                        "in": "query"
                    },
                    {
                        "minimum": 0,
                        "type": "integer",
                        "description": "Offset for pagination",
                        "name": "offset",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/dto.Partner"
                            }
                        }
                    },
                    "400": {
                        "description": "Invalid query parameters",
                        "schema": {
                            "$ref": "#/definitions/dto.HTTPStatus"
                        }
                    },
                    "500": {
                        "description": "Internal server error",
                        "schema": {
                            "$ref": "#/definitions/dto.HTTPStatus"
                        }
                    }
                }
            },
            "post": {
                "security": [
                    {
                        "CookieAuth": []
                    }
                ],
                "description": "Creates a new cosmetic product with provided details.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "partner"
                ],
                "summary": "Create a new cosmetic product",
                "parameters": [
                    {
                        "description": "Partner product data",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/dto.CreatePartnerRequest"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "$ref": "#/definitions/dto.CreatePartnerResponse"
                        }
                    },
                    "400": {
                        "description": "Invalid request body or validation error",
                        "schema": {
                            "$ref": "#/definitions/dto.HTTPStatus"
                        }
                    },
                    "409": {
                        "description": "Conflict: invalid partner format",
                        "schema": {
                            "$ref": "#/definitions/dto.HTTPStatus"
                        }
                    },
                    "500": {
                        "description": "Internal server error",
                        "schema": {
                            "$ref": "#/definitions/dto.HTTPStatus"
                        }
                    }
                }
            }
        },
        "/api/v1/info/partner/{id}": {
            "get": {
                "description": "Retrieves a partner product using its UUID.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "partner"
                ],
                "summary": "Get partner by ID",
                "parameters": [
                    {
                        "type": "string",
                        "format": "uuid",
                        "description": "Partner ID (UUID)",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/dto.GetByIdPartnerResponse"
                        }
                    },
                    "400": {
                        "description": "Validation error",
                        "schema": {
                            "$ref": "#/definitions/dto.HTTPStatus"
                        }
                    },
                    "404": {
                        "description": "Partner not found",
                        "schema": {
                            "$ref": "#/definitions/dto.HTTPStatus"
                        }
                    },
                    "500": {
                        "description": "Internal server error",
                        "schema": {
                            "$ref": "#/definitions/dto.HTTPStatus"
                        }
                    }
                }
            },
            "delete": {
                "security": [
                    {
                        "CookieAuth": []
                    }
                ],
                "description": "Deletes the partner with the given UUID.",
                "tags": [
                    "partner"
                ],
                "summary": "Delete partner by ID",
                "parameters": [
                    {
                        "type": "string",
                        "format": "uuid",
                        "description": "Partner ID (UUID)",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "204": {
                        "description": "Successfully deleted"
                    },
                    "400": {
                        "description": "Validation error",
                        "schema": {
                            "$ref": "#/definitions/dto.HTTPStatus"
                        }
                    },
                    "404": {
                        "description": "Partner not found",
                        "schema": {
                            "$ref": "#/definitions/dto.HTTPStatus"
                        }
                    },
                    "500": {
                        "description": "Internal server error",
                        "schema": {
                            "$ref": "#/definitions/dto.HTTPStatus"
                        }
                    }
                }
            },
            "patch": {
                "security": [
                    {
                        "CookieAuth": []
                    }
                ],
                "description": "Updates partner product fields by given ID.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "partner"
                ],
                "summary": "Update partner",
                "parameters": [
                    {
                        "type": "string",
                        "format": "uuid",
                        "description": "Partner ID (UUID)",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Updated partner fields",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/dto.UpdatePartnerRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/dto.UpdatePartnerResponse"
                        }
                    },
                    "400": {
                        "description": "Validation or binding error",
                        "schema": {
                            "$ref": "#/definitions/dto.HTTPStatus"
                        }
                    },
                    "404": {
                        "description": "Partner not found",
                        "schema": {
                            "$ref": "#/definitions/dto.HTTPStatus"
                        }
                    },
                    "500": {
                        "description": "Internal server error",
                        "schema": {
                            "$ref": "#/definitions/dto.HTTPStatus"
                        }
                    }
                }
            }
        },
        "/api/v1/order": {
            "post": {
                "description": "Creates a new leech order and send it to email.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "order"
                ],
                "summary": "Create a new leech order",
                "parameters": [
                    {
                        "description": "Leech order data",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/dto.CreateOrderRequest"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "$ref": "#/definitions/dto.CreateOrderResponse"
                        }
                    },
                    "400": {
                        "description": "Invalid request body or validation error",
                        "schema": {
                            "$ref": "#/definitions/dto.HTTPStatus"
                        }
                    },
                    "500": {
                        "description": "Internal server error",
                        "schema": {
                            "$ref": "#/definitions/dto.HTTPStatus"
                        }
                    }
                }
            }
        },
        "/api/v1/user": {
            "get": {
                "security": [
                    {
                        "CookieAuth": []
                    }
                ],
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "user"
                ],
                "summary": "Get current user info",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/dto.GetUserResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/dto.HTTPStatus"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/dto.HTTPStatus"
                        }
                    }
                }
            },
            "patch": {
                "security": [
                    {
                        "CookieAuth": []
                    }
                ],
                "description": "Information updating the current user under which the input is executed",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "user"
                ],
                "summary": "Update current user information",
                "parameters": [
                    {
                        "description": "User data",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/dto.UpdateCurrentUserRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/dto.UpdateCurrentUserResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/dto.HTTPStatus"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/dto.HTTPStatus"
                        }
                    }
                }
            }
        },
        "/api/v1/user/all": {
            "get": {
                "security": [
                    {
                        "CookieAuth": []
                    }
                ],
                "description": "Retrieves a list of users filtered by role, name, surname, email, etc. Only for admins",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "user"
                ],
                "summary": "Get users by filters",
                "parameters": [
                    {
                        "maximum": 100,
                        "minimum": 1,
                        "type": "integer",
                        "example": 10,
                        "description": "Max number of users to return",
                        "name": "limit",
                        "in": "query"
                    },
                    {
                        "minimum": 0,
                        "type": "integer",
                        "example": 0,
                        "description": "Pagination offset",
                        "name": "offset",
                        "in": "query"
                    },
                    {
                        "enum": [
                            0,
                            1,
                            2
                        ],
                        "type": "integer",
                        "example": 0,
                        "description": "Role enum (0–2)",
                        "name": "role",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "example": "\"Iv\"",
                        "description": "Filter by name prefix",
                        "name": "name_prefix",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "example": "\"Ivan\"",
                        "description": "Filter by surname prefix",
                        "name": "surname_prefix",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "example": "\"user@\"",
                        "description": "Filter by email prefix",
                        "name": "email_prefix",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/dto.User"
                            }
                        }
                    },
                    "400": {
                        "description": "Invalid query parameters",
                        "schema": {
                            "$ref": "#/definitions/dto.HTTPStatus"
                        }
                    },
                    "500": {
                        "description": "Internal server error",
                        "schema": {
                            "$ref": "#/definitions/dto.HTTPStatus"
                        }
                    }
                }
            }
        },
        "/api/v1/user/login": {
            "post": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "user"
                ],
                "summary": "Authenticate user",
                "parameters": [
                    {
                        "description": "Login credentials",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/dto.LoginUserRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/dto.LoginUserResponse"
                        },
                        "headers": {
                            "Set-Cookie": {
                                "type": "string",
                                "description": "user_auth_refresh_token=token; Path=/; HttpOnly; Secure; SameSite=Strict"
                            }
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/dto.HTTPStatus"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/dto.HTTPStatus"
                        }
                    }
                }
            }
        },
        "/api/v1/user/logout": {
            "post": {
                "security": [
                    {
                        "CookieAuth": []
                    }
                ],
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "user"
                ],
                "summary": "Logout user",
                "responses": {
                    "204": {
                        "description": "No Content",
                        "headers": {
                            "Set-Cookie": {
                                "type": "string",
                                "description": "user_auth_refresh_token=; expires=Thu, 01 Jan 1970 00:00:00 GMT; Path=/; HttpOnly"
                            }
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/dto.HTTPStatus"
                        }
                    }
                }
            }
        },
        "/api/v1/user/password": {
            "post": {
                "security": [
                    {
                        "CookieAuth": []
                    }
                ],
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "user"
                ],
                "summary": "Change user password",
                "parameters": [
                    {
                        "description": "Password change data",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/dto.ChangePasswordRequest"
                        }
                    }
                ],
                "responses": {
                    "204": {
                        "description": "No Content",
                        "headers": {
                            "Set-Cookie": {
                                "type": "string",
                                "description": "user_auth_refresh_token=token; Path=/; HttpOnly; Secure; SameSite=Strict"
                            }
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/dto.HTTPStatus"
                        }
                    },
                    "403": {
                        "description": "Forbidden",
                        "schema": {
                            "$ref": "#/definitions/dto.HTTPStatus"
                        }
                    }
                }
            }
        },
        "/api/v1/user/register": {
            "post": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "user"
                ],
                "summary": "Register new user",
                "parameters": [
                    {
                        "description": "Registration data",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/dto.RegisterUserRequest"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "$ref": "#/definitions/dto.RegisterUserResponse"
                        },
                        "headers": {
                            "Set-Cookie": {
                                "type": "string",
                                "description": "user_auth_refresh_token=token; Path=/; HttpOnly; Secure; SameSite=Strict"
                            }
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/dto.HTTPStatus"
                        }
                    },
                    "409": {
                        "description": "Conflict",
                        "schema": {
                            "$ref": "#/definitions/dto.HTTPStatus"
                        }
                    }
                }
            }
        },
        "/api/v1/user/{id}": {
            "get": {
                "security": [
                    {
                        "CookieAuth": []
                    }
                ],
                "description": "Get each user by id. Only for admins",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "user"
                ],
                "summary": "Get current user info",
                "parameters": [
                    {
                        "type": "string",
                        "description": "User ID (UUID)",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/dto.GetUserResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/dto.HTTPStatus"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/dto.HTTPStatus"
                        }
                    }
                }
            },
            "patch": {
                "security": [
                    {
                        "CookieAuth": []
                    }
                ],
                "description": "Information updating the current user under which the input is executed",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "user"
                ],
                "summary": "Update each user information",
                "parameters": [
                    {
                        "type": "string",
                        "description": "User ID (UUID)",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "User data",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/dto.UpdateEachUserRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/dto.UpdateEachUserResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/dto.HTTPStatus"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/dto.HTTPStatus"
                        }
                    }
                }
            }
        },
        "/ping": {
            "get": {
                "description": "Checking the server performance.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "ping"
                ],
                "summary": "Checking the server performance",
                "responses": {
                    "200": {
                        "description": "Successful check",
                        "schema": {
                            "$ref": "#/definitions/dto.PingResponse"
                        }
                    },
                    "500": {
                        "description": "Internal server error",
                        "schema": {
                            "$ref": "#/definitions/dto.HTTPStatus"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "dto.Category": {
            "type": "object",
            "required": [
                "id",
                "name"
            ],
            "properties": {
                "id": {
                    "type": "string",
                    "example": "3fa85f64-5717-4562-b3fc-2c963f66afa6"
                },
                "name": {
                    "type": "string",
                    "maxLength": 150,
                    "minLength": 1,
                    "example": "Shampoo"
                }
            }
        },
        "dto.ChangePasswordRequest": {
            "type": "object",
            "required": [
                "new_password",
                "old_password"
            ],
            "properties": {
                "new_password": {
                    "type": "string",
                    "format": "password",
                    "maxLength": 100,
                    "minLength": 8,
                    "example": "NewPass456!"
                },
                "old_password": {
                    "type": "string",
                    "format": "password",
                    "maxLength": 100,
                    "minLength": 8,
                    "example": "OldPass123!"
                }
            }
        },
        "dto.Cosmetics": {
            "description": "Contains product information such as category, title, description, and volume.",
            "type": "object",
            "properties": {
                "application_method": {
                    "type": "string",
                    "example": "Apply to wet hair, lather, rinse."
                },
                "category": {
                    "$ref": "#/definitions/dto.Category"
                },
                "description": {
                    "type": "string",
                    "example": "Suitable for daily use."
                },
                "id": {
                    "type": "string",
                    "example": "123e4567-e89b-12d3-a456-426614174000"
                },
                "is_hidden": {
                    "type": "boolean",
                    "example": false
                },
                "links": {
                    "$ref": "#/definitions/dto.Links"
                },
                "title": {
                    "type": "string",
                    "example": "Hair Shampoo"
                },
                "volume": {
                    "type": "integer",
                    "example": 250
                }
            }
        },
        "dto.CreateCategoryRequest": {
            "type": "object",
            "required": [
                "name"
            ],
            "properties": {
                "name": {
                    "type": "string",
                    "maxLength": 150,
                    "minLength": 1,
                    "example": "Shampoo"
                }
            }
        },
        "dto.CreateCategoryResponse": {
            "type": "object",
            "required": [
                "id",
                "name"
            ],
            "properties": {
                "id": {
                    "type": "string",
                    "example": "3fa85f64-5717-4562-b3fc-2c963f66afa6"
                },
                "name": {
                    "type": "string",
                    "maxLength": 150,
                    "minLength": 1,
                    "example": "Shampoo"
                }
            }
        },
        "dto.CreateCosmeticsRequest": {
            "type": "object",
            "required": [
                "category_id",
                "is_hidden",
                "title"
            ],
            "properties": {
                "application_method": {
                    "type": "string",
                    "maxLength": 500,
                    "minLength": 3,
                    "example": "Apply to wet hair, lather, rinse."
                },
                "category_id": {
                    "type": "string",
                    "example": "123e4567-e89b-12d3-a456-426614174000"
                },
                "description": {
                    "type": "string",
                    "maxLength": 3000,
                    "minLength": 3,
                    "example": "Suitable for daily use."
                },
                "is_hidden": {
                    "type": "boolean",
                    "example": false
                },
                "links": {
                    "$ref": "#/definitions/dto.Links"
                },
                "title": {
                    "type": "string",
                    "maxLength": 100,
                    "minLength": 3,
                    "example": "Hair Shampoo"
                },
                "volume": {
                    "type": "integer",
                    "maximum": 10000,
                    "minimum": 1,
                    "example": 250
                }
            }
        },
        "dto.CreateCosmeticsResponse": {
            "description": "Contains product information such as category, title, description, and volume.",
            "type": "object",
            "properties": {
                "application_method": {
                    "type": "string",
                    "example": "Apply to wet hair, lather, rinse."
                },
                "category": {
                    "$ref": "#/definitions/dto.Category"
                },
                "description": {
                    "type": "string",
                    "example": "Suitable for daily use."
                },
                "id": {
                    "type": "string",
                    "example": "123e4567-e89b-12d3-a456-426614174000"
                },
                "is_hidden": {
                    "type": "boolean",
                    "example": false
                },
                "links": {
                    "$ref": "#/definitions/dto.Links"
                },
                "title": {
                    "type": "string",
                    "example": "Hair Shampoo"
                },
                "volume": {
                    "type": "integer",
                    "example": 250
                }
            }
        },
        "dto.CreateOrderRequest": {
            "type": "object",
            "required": [
                "customer_info",
                "order_details"
            ],
            "properties": {
                "customer_info": {
                    "$ref": "#/definitions/dto.CustomerInfo"
                },
                "order_details": {
                    "$ref": "#/definitions/dto.OrderDetails"
                }
            }
        },
        "dto.CreateOrderResponse": {
            "type": "object",
            "properties": {
                "customer_info": {
                    "$ref": "#/definitions/dto.CustomerInfo"
                },
                "order_details": {
                    "$ref": "#/definitions/dto.OrderDetails"
                },
                "total_price": {
                    "type": "number",
                    "example": 3499.5
                }
            }
        },
        "dto.CreatePartnerRequest": {
            "type": "object",
            "required": [
                "name"
            ],
            "properties": {
                "description": {
                    "type": "string",
                    "maxLength": 500,
                    "example": "Leading supplier of industrial equipment"
                },
                "links": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/dto.PartnersLink"
                    }
                },
                "name": {
                    "type": "string",
                    "maxLength": 100,
                    "minLength": 1,
                    "example": "Backend's department"
                }
            }
        },
        "dto.CreatePartnerResponse": {
            "type": "object",
            "properties": {
                "description": {
                    "type": "string",
                    "example": "Leading supplier of industrial equipment"
                },
                "id": {
                    "type": "string",
                    "example": "123e4567-e89b-12d3-a456-426614174000"
                },
                "links": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/dto.PartnersLink"
                    }
                },
                "name": {
                    "type": "string",
                    "example": "Backend's department"
                }
            }
        },
        "dto.CustomerInfo": {
            "type": "object",
            "required": [
                "address",
                "email",
                "fio",
                "phone_number"
            ],
            "properties": {
                "address": {
                    "type": "string",
                    "maxLength": 200,
                    "minLength": 5,
                    "example": "г. Москва, ул. Ленина, д. 1, кв. 10"
                },
                "comment": {
                    "type": "string",
                    "maxLength": 500,
                    "example": "Позвоните за час до доставки"
                },
                "email": {
                    "type": "string",
                    "maxLength": 254,
                    "minLength": 6,
                    "example": "ivanov@example.com"
                },
                "fio": {
                    "type": "string",
                    "maxLength": 100,
                    "minLength": 2,
                    "example": "Иванов Иван Иванович"
                },
                "phone_number": {
                    "type": "string",
                    "example": "+79991234567"
                }
            }
        },
        "dto.GetByIdCategoryResponse": {
            "type": "object",
            "required": [
                "id",
                "name"
            ],
            "properties": {
                "id": {
                    "type": "string",
                    "example": "3fa85f64-5717-4562-b3fc-2c963f66afa6"
                },
                "name": {
                    "type": "string",
                    "maxLength": 150,
                    "minLength": 1,
                    "example": "Shampoo"
                }
            }
        },
        "dto.GetByIdCosmeticsResponse": {
            "description": "Contains product information such as category, title, description, and volume.",
            "type": "object",
            "properties": {
                "application_method": {
                    "type": "string",
                    "example": "Apply to wet hair, lather, rinse."
                },
                "category": {
                    "$ref": "#/definitions/dto.Category"
                },
                "description": {
                    "type": "string",
                    "example": "Suitable for daily use."
                },
                "id": {
                    "type": "string",
                    "example": "123e4567-e89b-12d3-a456-426614174000"
                },
                "is_hidden": {
                    "type": "boolean",
                    "example": false
                },
                "links": {
                    "$ref": "#/definitions/dto.Links"
                },
                "title": {
                    "type": "string",
                    "example": "Hair Shampoo"
                },
                "volume": {
                    "type": "integer",
                    "example": 250
                }
            }
        },
        "dto.GetByIdPartnerResponse": {
            "type": "object",
            "properties": {
                "description": {
                    "type": "string",
                    "example": "Leading supplier of industrial equipment"
                },
                "id": {
                    "type": "string",
                    "example": "123e4567-e89b-12d3-a456-426614174000"
                },
                "links": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/dto.PartnersLink"
                    }
                },
                "name": {
                    "type": "string",
                    "example": "Backend's department"
                }
            }
        },
        "dto.GetInfoResponse": {
            "type": "object",
            "required": [
                "description",
                "heading"
            ],
            "properties": {
                "description": {
                    "type": "string",
                    "maxLength": 500,
                    "minLength": 10,
                    "example": "We are a global leader in innovation and technology."
                },
                "heading": {
                    "type": "string",
                    "maxLength": 100,
                    "minLength": 3,
                    "example": "Welcome to our company"
                },
                "links": {
                    "type": "array",
                    "maxItems": 10,
                    "minItems": 0,
                    "items": {
                        "$ref": "#/definitions/dto.InfoLinks"
                    }
                },
                "schedule": {
                    "type": "array",
                    "maxItems": 7,
                    "minItems": 1,
                    "items": {
                        "$ref": "#/definitions/dto.ScheduleEntry"
                    }
                }
            }
        },
        "dto.GetUserResponse": {
            "type": "object",
            "properties": {
                "email": {
                    "type": "string",
                    "example": "user@example.com"
                },
                "id": {
                    "type": "string",
                    "example": "550e8400-e29b-41d4-a716-446655440000"
                },
                "name": {
                    "type": "string",
                    "example": "Ivan"
                },
                "role": {
                    "allOf": [
                        {
                            "$ref": "#/definitions/types.Role"
                        }
                    ],
                    "example": 0
                },
                "surname": {
                    "type": "string",
                    "example": "Ivanov"
                }
            }
        },
        "dto.HTTPStatus": {
            "type": "object",
            "properties": {
                "code": {
                    "type": "integer"
                },
                "message": {
                    "type": "string"
                }
            }
        },
        "dto.Hours": {
            "type": "object",
            "required": [
                "close",
                "open"
            ],
            "properties": {
                "close": {
                    "type": "string",
                    "example": "18:00"
                },
                "open": {
                    "type": "string",
                    "example": "09:00"
                }
            }
        },
        "dto.InfoLinks": {
            "type": "object",
            "required": [
                "href",
                "label"
            ],
            "properties": {
                "href": {
                    "type": "string",
                    "maxLength": 500,
                    "example": "https://instagram.com/company"
                },
                "label": {
                    "type": "string",
                    "maxLength": 50,
                    "minLength": 2,
                    "example": "Instagram"
                }
            }
        },
        "dto.Links": {
            "type": "object",
            "properties": {
                "ozon": {
                    "type": "string",
                    "maxLength": 500,
                    "example": "https://www.ozon.ru/product/gel-girudo-dr-nikonov-dlya-tela-100-ml-1907286044/?at=OgtEDAg59hR8AYgGimrnA9YIqYo9mocJYEzPjHR666Gm"
                },
                "wildberries": {
                    "type": "string",
                    "maxLength": 500,
                    "example": "https://www.wildberries.ru/catalog/344283033/detail.aspx"
                }
            }
        },
        "dto.LoginUserRequest": {
            "type": "object",
            "required": [
                "email",
                "password"
            ],
            "properties": {
                "email": {
                    "type": "string",
                    "maxLength": 254,
                    "minLength": 6,
                    "example": "user@example.com"
                },
                "password": {
                    "type": "string",
                    "format": "password",
                    "maxLength": 100,
                    "minLength": 8,
                    "example": "SecurePass123!"
                }
            }
        },
        "dto.LoginUserResponse": {
            "type": "object",
            "properties": {
                "email": {
                    "type": "string",
                    "example": "user@example.com"
                },
                "id": {
                    "type": "string",
                    "example": "550e8400-e29b-41d4-a716-446655440000"
                },
                "name": {
                    "type": "string",
                    "example": "Ivan"
                },
                "role": {
                    "allOf": [
                        {
                            "$ref": "#/definitions/types.Role"
                        }
                    ],
                    "example": 0
                },
                "surname": {
                    "type": "string",
                    "example": "Ivanov"
                }
            }
        },
        "dto.OrderDetails": {
            "type": "object",
            "required": [
                "package_type"
            ],
            "properties": {
                "leech_size_1": {
                    "type": "integer",
                    "maximum": 500,
                    "minimum": 0,
                    "example": 100
                },
                "leech_size_2": {
                    "type": "integer",
                    "maximum": 500,
                    "minimum": 0,
                    "example": 200
                },
                "leech_size_3": {
                    "type": "integer",
                    "maximum": 500,
                    "minimum": 0,
                    "example": 150
                },
                "package_type": {
                    "allOf": [
                        {
                            "$ref": "#/definitions/types.Package"
                        }
                    ],
                    "example": 1
                }
            }
        },
        "dto.Partner": {
            "type": "object",
            "properties": {
                "description": {
                    "type": "string",
                    "example": "Leading supplier of industrial equipment"
                },
                "id": {
                    "type": "string",
                    "example": "123e4567-e89b-12d3-a456-426614174000"
                },
                "links": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/dto.PartnersLink"
                    }
                },
                "name": {
                    "type": "string",
                    "example": "Backend's department"
                }
            }
        },
        "dto.PartnersLink": {
            "type": "object",
            "required": [
                "href",
                "label"
            ],
            "properties": {
                "href": {
                    "type": "string",
                    "maxLength": 2000,
                    "minLength": 1,
                    "example": "https://example.com"
                },
                "label": {
                    "type": "string",
                    "maxLength": 150,
                    "minLength": 1,
                    "example": "Official Website"
                }
            }
        },
        "dto.PingResponse": {
            "type": "object",
            "properties": {
                "message": {
                    "type": "string",
                    "example": "ok"
                }
            }
        },
        "dto.RegisterUserRequest": {
            "type": "object",
            "required": [
                "email",
                "name",
                "password",
                "surname"
            ],
            "properties": {
                "email": {
                    "type": "string",
                    "maxLength": 254,
                    "minLength": 6,
                    "example": "user@example.com"
                },
                "name": {
                    "type": "string",
                    "maxLength": 100,
                    "minLength": 2,
                    "example": "Ivan"
                },
                "password": {
                    "type": "string",
                    "format": "password",
                    "maxLength": 100,
                    "minLength": 8,
                    "example": "SecurePass123!"
                },
                "surname": {
                    "type": "string",
                    "maxLength": 100,
                    "minLength": 2,
                    "example": "Ivanov"
                }
            }
        },
        "dto.RegisterUserResponse": {
            "type": "object",
            "properties": {
                "email": {
                    "type": "string",
                    "example": "user@example.com"
                },
                "id": {
                    "type": "string",
                    "example": "550e8400-e29b-41d4-a716-446655440000"
                },
                "name": {
                    "type": "string",
                    "example": "Ivan"
                },
                "role": {
                    "allOf": [
                        {
                            "$ref": "#/definitions/types.Role"
                        }
                    ],
                    "example": 0
                },
                "surname": {
                    "type": "string",
                    "example": "Ivanov"
                }
            }
        },
        "dto.ScheduleEntry": {
            "type": "object",
            "required": [
                "hours",
                "weekday"
            ],
            "properties": {
                "hours": {
                    "$ref": "#/definitions/dto.Hours"
                },
                "weekday": {
                    "allOf": [
                        {
                            "$ref": "#/definitions/types.Weekday"
                        }
                    ],
                    "example": 1
                }
            }
        },
        "dto.UpdateCategoryRequest": {
            "type": "object",
            "required": [
                "id"
            ],
            "properties": {
                "id": {
                    "type": "string",
                    "example": "3fa85f64-5717-4562-b3fc-2c963f66afa6"
                },
                "name": {
                    "type": "string",
                    "maxLength": 150,
                    "minLength": 1,
                    "example": "Hair conditioner"
                }
            }
        },
        "dto.UpdateCategoryResponse": {
            "type": "object",
            "required": [
                "id",
                "name"
            ],
            "properties": {
                "id": {
                    "type": "string",
                    "example": "3fa85f64-5717-4562-b3fc-2c963f66afa6"
                },
                "name": {
                    "type": "string",
                    "maxLength": 150,
                    "minLength": 1,
                    "example": "Shampoo"
                }
            }
        },
        "dto.UpdateCosmeticsRequest": {
            "type": "object",
            "properties": {
                "application_method": {
                    "type": "string",
                    "maxLength": 500,
                    "minLength": 3,
                    "example": "Apply evenly and rinse well."
                },
                "category_id": {
                    "type": "string",
                    "example": "123e4567-e89b-12d3-a456-426614174000"
                },
                "description": {
                    "type": "string",
                    "maxLength": 3000,
                    "minLength": 3,
                    "example": "Updated product description."
                },
                "is_hidden": {
                    "type": "boolean",
                    "example": false
                },
                "links": {
                    "$ref": "#/definitions/dto.Links"
                },
                "title": {
                    "type": "string",
                    "maxLength": 100,
                    "minLength": 3,
                    "example": "New Hair Shampoo"
                },
                "volume": {
                    "type": "integer",
                    "maximum": 10000,
                    "minimum": 1,
                    "example": 500
                }
            }
        },
        "dto.UpdateCosmeticsResponse": {
            "description": "Contains product information such as category, title, description, and volume.",
            "type": "object",
            "properties": {
                "application_method": {
                    "type": "string",
                    "example": "Apply to wet hair, lather, rinse."
                },
                "category": {
                    "$ref": "#/definitions/dto.Category"
                },
                "description": {
                    "type": "string",
                    "example": "Suitable for daily use."
                },
                "id": {
                    "type": "string",
                    "example": "123e4567-e89b-12d3-a456-426614174000"
                },
                "is_hidden": {
                    "type": "boolean",
                    "example": false
                },
                "links": {
                    "$ref": "#/definitions/dto.Links"
                },
                "title": {
                    "type": "string",
                    "example": "Hair Shampoo"
                },
                "volume": {
                    "type": "integer",
                    "example": 250
                }
            }
        },
        "dto.UpdateCurrentUserRequest": {
            "type": "object",
            "properties": {
                "name": {
                    "type": "string",
                    "maxLength": 100,
                    "minLength": 2,
                    "example": "Ivan"
                },
                "surname": {
                    "type": "string",
                    "maxLength": 100,
                    "minLength": 2,
                    "example": "Petrov"
                }
            }
        },
        "dto.UpdateCurrentUserResponse": {
            "type": "object",
            "properties": {
                "email": {
                    "type": "string",
                    "example": "user@example.com"
                },
                "id": {
                    "type": "string",
                    "example": "550e8400-e29b-41d4-a716-446655440000"
                },
                "name": {
                    "type": "string",
                    "example": "Ivan"
                },
                "role": {
                    "allOf": [
                        {
                            "$ref": "#/definitions/types.Role"
                        }
                    ],
                    "example": 0
                },
                "surname": {
                    "type": "string",
                    "example": "Ivanov"
                }
            }
        },
        "dto.UpdateEachUserRequest": {
            "type": "object",
            "properties": {
                "email": {
                    "type": "string",
                    "maxLength": 254,
                    "minLength": 6,
                    "example": "user@example.com"
                },
                "name": {
                    "type": "string",
                    "maxLength": 100,
                    "minLength": 2,
                    "example": "Ivan"
                },
                "password": {
                    "type": "string",
                    "format": "password",
                    "maxLength": 100,
                    "minLength": 8,
                    "example": "SecurePass123!"
                },
                "surname": {
                    "type": "string",
                    "maxLength": 100,
                    "minLength": 2,
                    "example": "Ivanov"
                }
            }
        },
        "dto.UpdateEachUserResponse": {
            "type": "object",
            "properties": {
                "email": {
                    "type": "string",
                    "example": "user@example.com"
                },
                "id": {
                    "type": "string",
                    "example": "550e8400-e29b-41d4-a716-446655440000"
                },
                "name": {
                    "type": "string",
                    "example": "Ivan"
                },
                "role": {
                    "allOf": [
                        {
                            "$ref": "#/definitions/types.Role"
                        }
                    ],
                    "example": 0
                },
                "surname": {
                    "type": "string",
                    "example": "Ivanov"
                }
            }
        },
        "dto.UpdateInfoRequest": {
            "type": "object",
            "properties": {
                "description": {
                    "type": "string",
                    "maxLength": 500,
                    "minLength": 10,
                    "example": "Updated long description about the company."
                },
                "heading": {
                    "type": "string",
                    "maxLength": 100,
                    "minLength": 3,
                    "example": "Updated Heading"
                },
                "links": {
                    "type": "array",
                    "maxItems": 10,
                    "minItems": 0,
                    "items": {
                        "$ref": "#/definitions/dto.InfoLinks"
                    }
                },
                "schedule": {
                    "type": "array",
                    "maxItems": 7,
                    "minItems": 1,
                    "items": {
                        "$ref": "#/definitions/dto.ScheduleEntry"
                    }
                }
            }
        },
        "dto.UpdateInfoResponse": {
            "type": "object",
            "required": [
                "description",
                "heading"
            ],
            "properties": {
                "description": {
                    "type": "string",
                    "maxLength": 500,
                    "minLength": 10,
                    "example": "We are a global leader in innovation and technology."
                },
                "heading": {
                    "type": "string",
                    "maxLength": 100,
                    "minLength": 3,
                    "example": "Welcome to our company"
                },
                "links": {
                    "type": "array",
                    "maxItems": 10,
                    "minItems": 0,
                    "items": {
                        "$ref": "#/definitions/dto.InfoLinks"
                    }
                },
                "schedule": {
                    "type": "array",
                    "maxItems": 7,
                    "minItems": 1,
                    "items": {
                        "$ref": "#/definitions/dto.ScheduleEntry"
                    }
                }
            }
        },
        "dto.UpdatePartnerRequest": {
            "type": "object",
            "properties": {
                "description": {
                    "type": "string",
                    "maxLength": 500,
                    "example": "Updated description of the partner"
                },
                "links": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/dto.PartnersLink"
                    }
                },
                "name": {
                    "type": "string",
                    "maxLength": 100,
                    "minLength": 1,
                    "example": "New Name"
                }
            }
        },
        "dto.UpdatePartnerResponse": {
            "type": "object",
            "properties": {
                "description": {
                    "type": "string",
                    "example": "Leading supplier of industrial equipment"
                },
                "id": {
                    "type": "string",
                    "example": "123e4567-e89b-12d3-a456-426614174000"
                },
                "links": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/dto.PartnersLink"
                    }
                },
                "name": {
                    "type": "string",
                    "example": "Backend's department"
                }
            }
        },
        "dto.User": {
            "type": "object",
            "properties": {
                "email": {
                    "type": "string",
                    "example": "user@example.com"
                },
                "id": {
                    "type": "string",
                    "example": "550e8400-e29b-41d4-a716-446655440000"
                },
                "name": {
                    "type": "string",
                    "example": "Ivan"
                },
                "role": {
                    "allOf": [
                        {
                            "$ref": "#/definitions/types.Role"
                        }
                    ],
                    "example": 0
                },
                "surname": {
                    "type": "string",
                    "example": "Ivanov"
                }
            }
        },
        "types.Package": {
            "type": "integer",
            "enum": [
                0,
                1,
                2
            ],
            "x-enum-comments": {
                "PackagePeat": "Торф"
            },
            "x-enum-varnames": [
                "PackageWater",
                "PackageGel",
                "PackagePeat"
            ]
        },
        "types.Role": {
            "type": "integer",
            "enum": [
                0,
                1,
                2,
                3
            ],
            "x-enum-varnames": [
                "RoleUser",
                "RoleModerator",
                "RoleAdmin",
                "RoleSuperAdmin"
            ]
        },
        "types.Weekday": {
            "type": "integer",
            "enum": [
                0,
                1,
                2,
                3,
                4,
                5,
                6
            ],
            "x-enum-varnames": [
                "Monday",
                "Tuesday",
                "Wednesday",
                "Thursday",
                "Friday",
                "Saturday",
                "Sunday"
            ]
        }
    },
    "securityDefinitions": {
        "CookieAuth": {
            "description": "Authentication via HttpOnly cookies. System uses two cookies:\\n- ` + "`" + `user_auth_access_token` + "`" + ` (short-lived)\\n- ` + "`" + `user_auth_refresh_token` + "`" + ` (long-lived)\\n\\nAll protected endpoints require valid cookies to be automatically sent by browser.",
            "type": "apiKey",
            "name": "user_auth_access_token",
            "in": "cookie"
        }
    },
    "tags": [
        {
            "description": "The main check of server performance",
            "name": "ping"
        },
        {
            "description": "Leech order operations",
            "name": "order"
        },
        {
            "description": "User authentication and management",
            "name": "user"
        },
        {
            "description": "Work with authorization",
            "name": "auth"
        },
        {
            "description": "Cosmetics view and management",
            "name": "cosmetics"
        },
        {
            "description": "Category view and management",
            "name": "category"
        },
        {
            "description": "Information about the center",
            "name": "info"
        },
        {
            "description": "Information about center's partners",
            "name": "partner"
        }
    ]
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "пиявкипобеда.рф",
	BasePath:         "",
	Schemes:          []string{"https"},
	Title:            "Leech API",
	Description:      "Backend service for Leech-ru platform. Uses cookie-based authentication with HttpOnly tokens.",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
