name: Deploy to VDS

on:
  push:
    branches:
      - prod

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up SSH
        uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Deploy to VDS
        run: |
          ssh -o StrictHostKeyChecking=no ${{ secrets.VDS_USER_IP }} << 'EOF'
            cd ~/leech-ru
            git pull origin prod
            docker compose down
            docker compose up --build -d
          EOF
